// load client constants
export const LOAD_CLIENT_REQUEST = "LOAD_CLIENT_REQUEST";
export const LOAD_CLIENT_SUCCESS = "LOAD_CLIENT_SUCCESS";
export const LOAD_CLIENT_FAIL = "LOAD_CLIENT_FAIL";

export const LOGOUT_CLIENT_REQUEST = "LOGOUT_CLIENT_REQUEST";
export const LOGOUT_CLIENT_SUCCESS = "LOGOUT_CLIENT_SUCCESS";
export const LOGOUT_CLIENT_FAIL = "LOGOUT_CLIENT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
