// get all PROVIDER constants
export const GET_PROVIDER_REQUEST = "GET_PROVIDER_REQUEST";
export const GET_PROVIDER_SUCCESS = "GET_PROVIDER_SUCCESS";
export const GET_PROVIDER_FAIL = "GET_PROVIDER_FAIL";

// get single PROVIDER constants
export const GET_SINGLE_PROVIDER_REQUEST = "GET_SINGLE_PROVIDER_REQUEST";
export const GET_SINGLE_PROVIDER_SUCCESS = "GET_SINGLE_PROVIDER_SUCCESS";
export const GET_SINGLE_PROVIDER_FAIL = "GET_SINGLE_PROVIDER_FAIL";

// load PROVIDER constants
export const LOAD_PROVIDER_REQUEST = "LOAD_PROVIDER_REQUEST";
export const LOAD_PROVIDER_SUCCESS = "LOAD_PROVIDER_SUCCESS";
export const LOAD_PROVIDER_FAIL = "LOAD_PROVIDER_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
